# -*- coding: utf-8 -*-
"""TTS_Interface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/174iBsM96hsQReann2EYZP1mZPu8exoL1
"""

import streamlit as st
from PIL import Image
import pytesseract
from gtts import gTTS
import os
import base64

# إعداد الصفحة
st.set_page_config(page_title="Text to Speech App", layout="centered")

st.title("🔊 تحويل النص إلى صوت")
st.write("اختر إدخال صورة تحتوي على نص أو اكتب النص يدويًا، ثم اختر اللغة لتحويل النص إلى كلام.")

# اختيار طريقة الإدخال
option = st.radio("اختر طريقة الإدخال:", ["📷 إدخال صورة", "✍️ كتابة نص يدويًا"])

# اختيار اللغة
# الحصول على اللغات المتوفرة في Tesseract
available_langs = pytesseract.get_languages(config='')
lang = st.selectbox("اختر اللغة:", options=available_langs, index=available_langs.index("ara") if "ara" in available_langs else 0)


# إدخال النص أو الصورة
text = ""

if option == "📷 إدخال صورة":
    uploaded_image = st.file_uploader("ارفع صورة", type=["png", "jpg", "jpeg"])
    if uploaded_image is not None:
        image = Image.open(uploaded_image)
        st.image(image, caption="الصورة التي تم رفعها", use_column_width=True)
        text = pytesseract.image_to_string(image, lang=lang)
        st.success("✅ تم استخراج النص من الصورة.")

elif option == "✍️ كتابة نص يدويًا":
    text = st.text_area("اكتب النص هنا:")

# زر التحويل
if st.button("🎤 تحويل النص إلى صوت"):
    if text.strip() == "":
        st.error("من فضلك أدخل نصًا أولاً.")
    else:
        tts = gTTS(text, lang=lang)
        tts.save("output.mp3")
        st.audio("output.mp3", format="audio/mp3", start_time=0)

        # زر التحميل
        with open("output.mp3", "rb") as audio_file:
            audio_bytes = audio_file.read()
            b64 = base64.b64encode(audio_bytes).decode()
            href = f'<a href="data:audio/mp3;base64,{b64}" download="output.mp3">📥 تحميل الصوت</a>'
            st.markdown(href, unsafe_allow_html=True)